// Fonts
import { fredoka, quicksand } from 'public/fonts';

// Provider
import QueryProvider from '@/providers/query-client-provider';

// Types
import type { Metadata } from 'next';
import { JSX } from 'react';

// Toast
import { Toaster } from 'react-hot-toast';

// CSS
import './globals.css';
import { AuthProvider } from '@/context/auth.context';
import { FCMProvider } from '@/context/fcm.context';

export const metadata: Metadata = {
  title: 'Accomplishment Tracking',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${fredoka.variable} ${quicksand.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            <FCMProvider>
              <Toaster />
              {children}
            </FCMProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
